"""Add show_answer

Revision ID: 0f513e46f279
Revises: 43f9ed2a529e
Create Date: 2025-02-17 11:48:00.765863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f513e46f279'
down_revision: Union[str, None] = '43f9ed2a529e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamestatus', sa.Column('show_answer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gamestatus', 'show_answer')
    # ### end Alembic commands ###
