"""Add timer

Revision ID: 43f9ed2a529e
Revises: 1f564fe1e9bc
Create Date: 2025-02-15 18:48:04.076086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f9ed2a529e'
down_revision: Union[str, None] = '1f564fe1e9bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamestatus', sa.Column('timer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gamestatus', 'timer')
    # ### end Alembic commands ###
