"""init

Revision ID: 793bddf2308b
Revises: a616d545ee2a
Create Date: 2025-04-22 23:47:33.626108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793bddf2308b'
down_revision: Union[str, None] = 'a616d545ee2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamestatus', sa.Column('timer_seconds', sa.Integer(), nullable=True))
    op.alter_column('gamestatus', 'sections',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('gamestatus', 'current_question',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('gamestatus', 'answer_for_current_question',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('gamestatus', 'spectator_display_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_gamestatus_id'), 'gamestatus', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gamestatus_id'), table_name='gamestatus')
    op.alter_column('gamestatus', 'spectator_display_mode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('gamestatus', 'answer_for_current_question',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('gamestatus', 'current_question',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('gamestatus', 'sections',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('gamestatus', 'timer_seconds')
    # ### end Alembic commands ###
