"""init

Revision ID: 98ffa5089b68
Revises: 793bddf2308b
Create Date: 2025-04-29 15:17:02.450526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ffa5089b68'
down_revision: Union[str, None] = '793bddf2308b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gamestatus', 'timer_seconds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamestatus', sa.Column('timer_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
