"""add images in question table

Revision ID: bca55b0db63d
Revises: e63d3d1ea865
Create Date: 2025-02-07 16:04:01.168511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca55b0db63d'
down_revision: Union[str, None] = 'e63d3d1ea865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_image', sa.String(length=1000), nullable=False))
    op.add_column('questions', sa.Column('answer_image', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'answer_image')
    op.drop_column('questions', 'question_image')
    # ### end Alembic commands ###
