"""add cascade delete 2.0

Revision ID: c1b29a9258d2
Revises: a598832f4abc
Create Date: 2025-02-06 21:34:52.616175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b29a9258d2'
down_revision: Union[str, None] = 'a598832f4abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answers_user_id_fkey', 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key('answers_user_id_fkey', 'answers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
